version: "3.4"

services:
  app:
    build:
      context: .
      target: production
    restart: on-failure
    depends_on: [database]
    ports: ["8000:8000"]
    environment:
      - MARIADB_HOST=database
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    networks: [haldis]
  database:
    image: mariadb:10.8
    hostname: database
    restart: on-failure
    environment:
      - MARIADB_DATABASE
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    networks: [haldis]
    volumes: [haldis_data:/var/lib/mysql]
networks:
  haldis:
volumes:
  haldis_data: